on:
  push:
    branches:
      - master
jobs:
  build-and-upload-to-docker-hub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: indrafajar/pelanggaran-fe-saas:latest  # Update this
          build-args: |
            BASE_URL=${{ secrets.BASE_URL }}

  deploy-vm2:
    runs-on: ubuntu-latest
    needs: build-and-upload-to-docker-hub
    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.VM_SSH_KEY }}
      - name: Deploy to VM
        env:
          HOST: ${{ secrets.VM_HOST }}
          USER: ${{ secrets.VM_USERNAME }}
          PORT: ${{ secrets.VM_PORT }}
        run: |
          ssh -o StrictHostKeyChecking=no -p "${PORT}" $USER@$HOST << 'EOF'
            docker pull indrafajar/pelanggaran-fe-saas:latest
            if [ "$(docker ps -aq -f name=pelanggaran-fe-run)" ]; then
              if [ "$(docker ps -q -f name=pelanggaran-fe-run)" ]; then
                docker stop pelanggaran-fe-run
              fi
              docker container rm pelanggaran-fe-run
              docker run -d --name pelanggaran-fe-run --restart unless-stopped --network my-app -p 5000:3000 indrafajar/pelanggaran-fe-saas:latest
            else
              docker run -d --name pelanggaran-fe-run --restart unless-stopped --network my-app -p 5000:3000 indrafajar/pelanggaran-fe-saas:latest
            fi
            docker image prune -f
          EOF